
   
version: "3.7"
services:
  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - network

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - network

  plausible:
    image: plausible/analytics:stable
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    expose:
      - 8000
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.analytics.loadbalancer.server.port=8000
        - traefik.http.routers.analytics.rule=Host(`${BASE_URL}`)
        - traefik.http.routers.analytics.entrypoints=http,https
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - network
      - public-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}   
      ADMIN_USER_NAME: ${ADMIN_USER_NAME}  
      ADMIN_USER_PWD: ${ADMIN_USER_PWD}   
      BASE_URL: https://${BASE_URL}   
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      CLICKHOUSE_DATABASE_URL: http://plausible_events_db:8123/plausible_events_db
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@plausible_db/${POSTGRES_DB}
      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION}

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  network:
  public-network:
    name: public-network
    external: true
