version: '3.8'
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-config:/etc/gitlab-runner
    restart: unless-stopped

  register-runner-job:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - runner-config:/etc/gitlab-runner
    restart: "no"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    command: >
      register
      --non-interactive
      --executor "docker"
      --url "${GITLAB_URL}"
      --registration-token "${GITLAB_RUNNER_REGISTRATION_TOKEN}"
      --name "${GITLAB_RUNNER_NAME}"
      --tag-list "${GITLAB_RUNNER_TAGS}"
      --run-untagged "${GITLAB_RUNNER_RUN_UNTAGGED}"
      --locked "${GITLAB_RUNNER_LOCKED}"
      --access-level "${GITLAB_RUNNER_RUN_ONLY_PROTECTED}"
      --docker-image "${GITLAB_RUNNER_IMAGE}"
      --docker-privileged
      --docker-volumes "/certs/client"

volumes:
  runner-config: